name: sheep_animation
description: Package that makes creating Flutter animation easier.
version: 1.0.0
homepage: https://sheep-apps.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
